# Generated by Django 6.0.1 on 2026-02-04 15:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/products')),
        ),
    ]
