# Generated by Django 6.0.1 on 2026-02-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_carts_delete_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='sessionid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
